name: Rugs CI
on:
  push:
  pull_request:

jobs:
  check:
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2
      - name: Update rust
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version
      - name: Lint
        run: |
          cd rugs
          cargo fmt -- --check
          # cargo clippy -- -D warnings
      - name: Test
        run: |
          cd rugs
          cargo check
          cargo test --all
      - name: Build
        run: |
          cd rugs
          cargo build --release
